### ISSUE TITLE
'Go to definition' does not work in v0.10.0

### ISSUE THREAD

**Issue by MikeChou** [rubyide/vscode-ruby#81]
### Your environment

- `vscode-ruby` version: 0.10.0
- Ruby version: ruby 2.3.1p112
- VS Code version: 1.6.1
- Operating System: Ubuntu 16.10
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
Press F12 (or choose 'Go to definition' on right click menu) when cursor is on a method/module name, then editor jump to the definition of this method/module. (vscode-ruby v0.9.0 works like this.)

### Actual behavior
 (After upgraded vscode-ruby to v0.10.0) Nothing happens after press F12. And there is no 'Go to definition' in right click menu.

### Steps to reproduce the problem
1. Using vscode-ruby v0.9.0 and this function works as expected.
2. Upgrade vscode-ruby to v0.10.0 and restart vscode
3. Cannot use this function in the same workspace
4. Try to restart vscode, still not working
5. Check ruby,rebase,ruby-debug-ide, they are all installed

**Comment by HookyQR** [comment]
Looking into it now. I may have missed something in the refactor.

**Comment by HookyQR** [comment]
I'm not having the same problem. Can you open the developer tools console and see if there is something there that's relevant. (Help -> Open Developer Tools -> Console)

**Comment by MikeChou** [comment]
Yeah. There are some errors.
```
workbench.main.js:121 [Extension Host] Activating extension `rebornix.Ruby` failed:  Cannot find module './lint/LintCollection'(anonymous function) @ workbench.main.js:121
workbench.main.js:121 [Extension Host] Here is the error stack:  Error: Cannot find module './lint/LintCollection'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.N.n._load (/home/mike/.local/share/umake/ide/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:19970)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mike/.vscode/extensions/rebornix.Ruby-0.10.0/ruby.js:8:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by HookyQR** [comment]
It's a case sensitivity issue. It doesn't show up for me because my main machine is a Mac (which is case insensitive). As a work around, bring up the *Go to File* pallet (`Ctrl+P`?) and enter:

`/home/mike/.vscode/extensions/rebornix.Ruby-0.10.0/ruby.js:8`

Change the capital 'LintCollection' to 'lintCollection', save, then reload VS Code.

Sorry. Will fix now.

**Comment by HookyQR** [comment]
Have pushed changes straight to master. @rebornix, can we please have a patch release.

**Comment by MikeChou** [comment]
@HookyQR 
Thanks.
And I found another one:
`rebornix.Ruby-0.10.0/lint/lintCollection.js:4`
`LintResults` should be `lintResults`
After changing these two letters, `Go to definition` works like a charm.

**Comment by HookyQR** [comment]
Thanks Mike. Saw that too. Fixed both. Just waiting for CI to finish on the PR then @rebornix should be able to patch and publish.
